import React from "react";
import type { Metadata } from "next";
import { Ma_Shan_Zheng } from "next/font/google";
import "./globals.css";

const font = Ma_Shan_Zheng({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mashan",
  display: "swap",
  preload: true
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className={font.className}>
      <body>{children}</body>
    </html>
  );
}
